### ISSUE TITLE
Support aarch64 CPUs (ARMv8 / ARM64)

### ISSUE THREAD

**Issue by staylor774** [edsiper/flb_libco#1]
libco needs native support for aarch64 CPUs (such as NVIDIA TX1/TX2). There is ARMv7 support, however the ARMv7 `co_swap_function` instructions crash (SIGILL) on an aarch64 CPU.

I have gotten fluent-bit to compile and run on aarch64 by modifying sjlj.c.

sjlj.c needs two changes:
`#include "settings.h"`
... and `co_create`  signature appears to be wrong. I've added a `size_t*`:
`cothread_t co_create(unsigned int size, void (*coentry)(void), size_t* unused) {`

I can't submit a patch due to corporate restrictions, but I hope someone can integrate a fix into master. :)

**Comment by edsiper** [comment]
FYI: I have submitted the fixes for sjlj

**Comment by edsiper** [comment]
I;ve updated libco inclusion, if __aarch64__ is detected, it will switch to sjlj, would you please check the changes ?

**Comment by staylor774** [comment]
@edsiper Checked that changes work in fluent-bit. I'll close this issue. Thanks for your support, love your work!

**Comment by edsiper** [comment]
FYI: native aarch64 support has been merged.
